# conda env update -f environment.yml to update environment
name: satcast
channels:
  - defaults
dependencies:
  - python=3.13.2
  - pandas=2.2.3
  - numpy=2.2.4
  - scikit-learn=1.6.1
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - jupyterlab=4.3.4
  - pyarrow=19.0.0
  - fastparquet=2024.11.0
  - statsmodels=0.14.4
